### ISSUE TITLE
multiples map with the same name in different classes

### ISSUE THREAD

**Issue by gferreux** [logstash-plugins/logstash-codec-protobuf#33]
Hi,

Not sure if this is related to the codec or the way logstash "include" the codec config, but i cannot manage to have multiples classes with the same variables names when they are of type "map".
It look like, the codec create some map.key , map.value fields that cannot be defined multiples time with the same map names, event in differents classes.

Here is an example:

- logstash input:
```
  kafka {
    topics => ["event1"]
    ...
    codec => protobuf
    {
      class_name => "Event1"
      include_path => ['/usr/share/logstash/protobuf/event1_pb.rb']
      protobuf_version => 3
      }
  }

  kafka {
    topics => ["event2"]
    ...
    codec => protobuf
    {
      class_name => "Event2"
      include_path => ['/usr/share/logstash/protobuf/event2_pb.rb']
      protobuf_version => 3
      }
  }
```

- protobuf:

1. event1_pb.rb
```
  require 'google/protobuf'
  Google::Protobuf::DescriptorPool.generated_pool.build do
    add_message "event1" do
      optional :name, :string, 1
      map :mymap, :string, :string, 2
    end
  end
  ...
```
2. event2_pb.rb
```
  require 'google/protobuf'
  Google::Protobuf::DescriptorPool.generated_pool.build do
    add_message "event2" do
      optional :name, :string, 1
      map :mymap, :string, :string, 2
    end
  end
  ...
```

- logstahs logs: `"mymap.key: \"key\" is already defined in \"mymap\"."`
```
[2019-02-12T14:59:06,675][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"RuntimeError", :message=>"ext.key: \"key\" is already defined in \"ext\".", :backtrace=>["com/google/protobuf/jruby/RubyDescriptorPool.java:84:in `build'", "/usr/share/logstash/protobuf/exchange_message_pb.rb:7:in `<main>'", "org/jruby/RubyKernel.java:955:in `require'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/usr/share/logstash/vendor/local_gems/2a798686/logstash-codec-protobuf-1.1.1/lib/logstash/codecs/protobuf.rb:419:in `load_protobuf_definition'", "/usr/share/logstash/vendor/local_gems/2a798686/logstash-codec-protobuf-1.1.1/lib/logstash/codecs/protobuf.rb:111:in `block in register'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/local_gems/2a798686/logstash-codec-protobuf-1.1.1/lib/logstash/codecs/protobuf.rb:111:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:18:in `initialize'", "org/logstash/plugins/PluginFactoryExt.java:233:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:166:in `plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "(eval):1:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:42:in `block in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:92:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:92:in `exclusive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:38:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:317:in `block in converge_state'"]}
```
(if i rename event2.mymap to event2.anothermap, it works ok)

Could you point me to the right direction ?
thanks

**Comment by yaauie** [comment]
Unfortunately, it looks like this is a long-standing issue with the official jruby protobuf implementation:

https://github.com/protocolbuffers/protobuf/issues/3650

***

I can replicate in a single protobuf definition file, without logstash

> ~~~
> require 'google/protobuf'
> 
> Google::Protobuf::DescriptorPool.generated_pool.build do
>   add_message "event1" do
>     optional :name, :string, 1
>     map :mymap, :string, :string, 2
>   end
>   add_message "event2" do
>     optional :name, :string, 1
>     map :mymap, :string, :string, 2
>   end
> end
> ~~~
> -- `events_pb.rb`

~~~
╭─{ yaauie@castrovel:~/src/elastic/pr-scratch/logstash-codec-protobuf/33-same-key }
╰─○ ruby --version
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 Java HotSpot(TM) 64-Bit Server VM 25.152-b16 on 1.8.0_152-b16 +jit [darwin-x86_64]
[success]

╭─{ yaauie@castrovel:~/src/elastic/pr-scratch/logstash-codec-protobuf/33-same-key }
╰─○ gem install google-protobuf --version 3.5.0.pre # latest jruby-platform version
Fetching: google-protobuf-3.5.0.pre-java.gem (100%)
Successfully installed google-protobuf-3.5.0.pre-java
1 gem installed
gem install google-protobuf --version 3.5.0.pre  19.76s user 0.67s system 354% cpu 5.758 total
[success (6.000s)]

╭─{ yaauie@castrovel:~/src/elastic/pr-scratch/logstash-codec-protobuf/33-same-key }
╰─○ ruby events_pb.rb
RuntimeError: mymap.key: "key" is already defined in "mymap".
   build at com/google/protobuf/jruby/RubyDescriptorPool.java:84
  <main> at events_pb.rb:2
ruby events_pb.rb  6.59s user 0.33s system 300% cpu 2.301 total
[error: 1]

~~~

**Comment by IngaFeick** [comment]
@yaauie thanks for the info!
@gferreux I'm closing this because it's not related to the codec.
